version: '{build}'
environment:
  CLI_VERSION: latest
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
image: Visual Studio 2017
configuration:
    - Release
skip_tags: true
before_build:
    - dotnet tool install -g GitVersion.Tool --version 4.0.1-beta1-58
    - dotnet gitversion /l console /output buildserver
build_script:
    - dotnet build -c Release -p:Version=%GitVersion_NuGetVersion%
test_script:
    - dotnet test -c Release --no-build
artifacts:
- path: .\**\*.nupkg
  name: NuGet
nuget:
  disable_publish_on_pr: true 
deploy:
- provider: NuGet
  api_key:
    secure: K7GBfAz5cr3lqVzn2+KbM45GA2ZeDjOpgnDU2jpw76PxBL2Qph3OBcfXWuGb+wwD
  on:
    branch:
    - master
    - /release\/[0-9]\.[0-9]/